### ISSUE TITLE
null-safe分支的示例不是null-safe的

### ISSUE THREAD

**Issue by honjow** [Nayuta-D/fps_monitor#8]
导致不知道2.0怎么使用。 不知道overlayState哪来的

**Comment by Nayuta403** [comment]
![image](https://user-images.githubusercontent.com/40540394/124210610-4ea6fb00-db1e-11eb-91da-a822980aa543.png)
![image](https://user-images.githubusercontent.com/40540394/124210801-a3e30c80-db1e-11eb-8e4d-b60ca13a769e.png)
你看下，用法应该是一样的

**Comment by SheepYang1993** [comment]
非空判断没有加， @Nayuta403 非空的示例代码确实是不行

要加判断才行
```dart

class MyApp extends StatelessWidget {
  MyApp() {
    RouterUtil.init();
  }

  @override
  Widget build(BuildContext context) {
    ///声明NavigatorState的GlobalKey
    GlobalKey<NavigatorState> globalKey = GlobalKey();

    ///获取overLayState
    SchedulerBinding.instance!.addPostFrameCallback((t) {
      if (globalKey.currentState?.overlay != null) {
        overlayState = globalKey.currentState!.overlay!;
      }
    });
    /// 省略代码
  }
}
```

**Comment by Nayuta403** [comment]
是example里面没有改么，我看lib文件下是null-safe的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Nayuta403/fps_monitor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月29日(星期四) 下午5:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Nayuta403/fps_monitor] null-safe分支的示例不是null-safe的 (#8)





 
非空判断没有加， @Nayuta403 非空的示例代码确实是不行
